FROM nvidia/cuda:10.0-base-ubuntu18.04
LABEL maintainer "antoine.charbel@inmind.ai"

# The commands below install Cuda and libcudnn in order for the code to run on the GPU
ENV CUDNN_VERSION 7.4.2.24
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

COPY docker/requirements.txt .

COPY src/main /main

RUN apt-get update && apt-get install -y --no-install-recommends \
  libcudnn7=$CUDNN_VERSION-1+cuda10.0 && \
  apt-mark hold libcudnn7 && \
  rm -rf /var/lib/apt/lists/*

# Install python dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
  locales \
  python3 \
  python3-pip \
  python3-setuptools \
  python3-dev \
  pkg-config\
  cuda-command-line-tools-10-0 \
  cuda-cublas-10-0 \
  cuda-cufft-10-0 \
  cuda-curand-10-0 \
  cuda-cusolver-10-0 \
  cuda-cusparse-10-0 \
  && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir -r requirements.txt

# Set the locale (required for uvicorn)
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
  dpkg-reconfigure --frontend=noninteractive locales && \
  update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8 

WORKDIR /main

EXPOSE 4343

CMD ["uvicorn", "start:app", "--host", "0.0.0.0", "--port", "4343"]
